name: Schedule

on:
  schedule:
    - cron: '*/30 * * * *' # Runs every 30 minutes
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: |
          npm install -g @usebruno/cli
          npm install -g allure-commandline
      - name: Run tests
        working-directory: ./OpenAQ
        continue-on-error: true
        run: bru run --env Live --reporter-junit junit.xml
      - name: Prepare Allure results
        working-directory: ./OpenAQ
        if: always()
        run: |
          mkdir -p allure-results
          cp junit.xml allure-results/
      - name: Load test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      - name: Copy history to allure-results
        working-directory: ./OpenAQ
        if: always()
        continue-on-error: true
        run: |
          if [ -d "../gh-pages/history" ]; then
            mkdir -p allure-results/history
            cp -r ../gh-pages/history/* allure-results/history/
          fi
      - name: Generate Allure report
        working-directory: ./OpenAQ
        if: always()
        run: |
          allure generate allure-results --clean -o allure-report --report-format junit
      - name: Publish to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./OpenAQ/allure-report
